### PR TITLE
Added support for Chi Square distance

### PR DESCRIPTION
**Pull request by DavidBerdik**
Added support for Chi Square distance and added unit test for it

### CODE REVIEW

**Comment by DavidBerdik** [comment]
As far as I can tell, the Codacy and Travis CI errors are not related to issues with my code.

**Comment by LucaCappelletti94** [comment]
Thank you for your pull request, I will look into it most likely during this weekend. Thanks!

**Comment by DavidBerdik** [comment]
You're welcome! Thank you for developing this library. It has saved me a lot of time. Instead of implementing all of these distance functions myself, I only had to do Chi Square.

**Comment by DavidBerdik** [comment]
In case anyone wants to play with a version of this library that has my additions. Needless to say, it's an unofficial, experimental build.

```
pip3 install https://github.com/DavidBerdik/dictances/releases/download/v1.5.0_chi_beta/dictances-1.5.0_chi_beta-py3-none-any.whl
```

**Comment by LucaCappelletti94** [comment]
I have refactored the tests, Travis integration etc... Would you consider updating your pull request accordingly? Otherwise, I'll do it myself when I'll get time.

Thanks!

**Comment by LucaCappelletti94** [comment]
Is [the chi square from scipy](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.stats.chisquare.html) a good reference function for this method? We can use that in the new test suite.

**Comment by DavidBerdik** [comment]
I do not know scipy well enough to answer that with absolute confidence, but I believe it should be. I was actually about to push a commit that adds back the utility module that the old tests use so that the tests that I wrote would work. Should I hold off on doing so?

**Comment by LucaCappelletti94** [comment]
Yes, if you see the new test module you just need to add your function and a reference method to the dictionary of the metrics to test.

**Comment by DavidBerdik** [comment]
Like the `bhattacharyya_reference.py` module? Sorry, I'm finding the new test layout confusing.

**Comment by LucaCappelletti94** [comment]
Sure, no problem. All the unit tests are executed [in the main test](https://github.com/LucaCappelletti94/dictances/blob/master/tests/test_dictances_against_references.py), that tests for simmetry etc.. and test against a given reference method, when available.

You just need to add the method to the dictionary, and that's it.

**Comment by LucaCappelletti94** [comment]
Ok, the new issue from scipy is a weird one. Could you implement a version for vectors of the chi square distance? We could use something like that to test the one for dictionaries.

**Comment by DavidBerdik** [comment]
I am looking to see if there is a way to easily do it with scipy or numpy but I cannot find anything. I am not sure why Chi Square distance is so hard to find implementations of.

**Comment by LucaCappelletti94** [comment]
I'm reading from the documentation [scipy.stats.chisquare](https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.stats.chisquare.html) that the method returns a Tuple, containing the score and the pvalue. I would suggest to make a wrapper function that returns the first value, the score, for the test.

**Comment by DavidBerdik** [comment]
Okay I can. How would you like that to be done in the context of the test suite?

**Comment by LucaCappelletti94** [comment]
I would just add the method in the utils and import it in the main test file. Does that seem ok?

**Comment by DavidBerdik** [comment]
Sure! I will try to get to it soon. If I cannot, you are of course welcome to do it for me.

**Comment by DavidBerdik** [comment]
So I added a wrapper function that callls the scipy function and returns the first entry from the tuple as you requested, but it is not working. Do I have to take two numpy arrays as parameters like Bhattacharyya distance does?

**Comment by DavidBerdik** [comment]
I will add a test for normalized chi square as soon as I can.

**Comment by LucaCappelletti94** [comment]
Perfect! Sorry if I'm leaving it all to you, I'm head deep into some deadlines and I'm wrapping another project to automatically plot nice looking histograms, which sounded easier said than done.

**Comment by DavidBerdik** [comment]
No problem. Good luck with your other project!

**Comment by LucaCappelletti94** [comment]
I have removed the Prospector__9999 check from Codacy, I have no idea why they put such a thing on python 3 projects.

**Comment by DavidBerdik** [comment]
Thank you. I was just about to post complaining about that.

**Comment by DavidBerdik** [comment]
It's still complaining about my function signatures. I don't know what to do from here, so I will let you take over.

**Comment by LucaCappelletti94** [comment]
I have no idea why it keeps adding this test, everything is in order, I'll merge the pull request.

Thanks!

**Comment by DavidBerdik** [comment]
You're welcome! Thanks for developing this library! Out of curiosity, how soon will the update hit PyPI? I am not sure how the PyPI release process works.

**Comment by LucaCappelletti94** [comment]
As soon as I understand why sonar has decided to start crashing I'll push the new version to pipy. It should be available an hour or so afterwards tops, by running `pip install dictances --upgrade`.

**Comment by LucaCappelletti94** [comment]
I have published the new version, I have no idea as to why sonar has started going off and I see no useful information in the issues with similar exceptions.

**Comment by DavidBerdik** [comment]
Great! Thank you.

**Pull request merged**
